### PR TITLE
Learn loops

### PR DESCRIPTION
**Pull request by selvialbert**
For loop programs for odd & even numbers

### CODE REVIEW

**Comment by selvialbert** [comment]
Sorry, Leo made mistake with creating a branch. 
Can you please review only the last four commits?
for_loop_odd_numbers
for_loop_even_numbers
while_loop_odd_numbers
for_loop_even_numbers

**Review by leocyriac — COMMENTED** [review]
Don't see "for loop" for odd numbers. Others look good.

**Comment by selvialbert** [comment]
for_loop_odd_numbers is now added, Leo. Sorry I am not sure how it got missed.

**Review by leocyriac — APPROVED** [review]
All good, Please merge

**Pull request merged**
